### ISSUE TITLE
Conflict with Laravel Cashier

### ISSUE THREAD

**Issue by dapehe94** [overtrue/laravel-subscribe#16]
Hi
This package conflicts if you have Laravel Cashier installed.

`Trait method Overtrue\LaravelSubscribe\Traits\Subscriber::subscriptions has not been applied as App\Models\User::subscriptions, because of collision with Laravel\Cashier\Billable::subscriptions`

It would be nice to fix it

Thanks

**Comment by overtrue** [comment]
Hi, @dapehe94  

Yes, because the trait of both packages have the same name method which causes conflict, I originally tried to use the alias method to avoid this problem, but after I read the source code of both packages, I found that the method name is still referenced in both packages, so even if you use the alias to solve the conflict, it will still cause other bugs, so it looks like you have to give up on using both of them at the same time.

Or you can follow the code of this package to implement it in your project by modifying the method name to realize it, I can't modify the method name of the package directly because it will break the compatibility of other users, I hope you can understand.

**Comment by dapehe94** [comment]
Thank you @overtrue 
I've clone the package...

**Comment by dapehe94** [comment]
In case anyone needs it, here it is:
[https://github.com/dapehe94/laravel-subscribe](url)
